---
# handlers

- name: start mysql
  service: 
    name: mysql
    state: started
    enabled: true
  become: yes

- name: restart mysql
  service: 
    name: mysql
    state: restarted
  become: yes
