---
# create virtual host directory, place and enable new virtual host

- name: create virtual host directory
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data 
    group: www-data 
    mode: 0777
  become: yes
  with_items:
    - /var/www/site
    - /var/www/site/htdocs

- name: copy virtual host file
  copy: 
    src: /vagrant/config/vhost80.conf 
    dest: /etc/apache2/sites-available/vhost80.conf
    owner: root 
    group: root 
    mode: 0644
  become: yes

- name: enable new virtual host
  command: a2ensite vhost80.conf
  become: yes

- name: disable default virtual host
  command: a2dissite 000-default.conf
  become: yes
  notify:
    - restart apache2
    - ensure apache2 running
